import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navigation from "@/components/navigation";
import { ThemeProvider } from '@mui/material/styles';
import theme from './theme';
import { CssBaseline } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  let nav = <Navigation />

  return (
    <html>      
      <body className={inter.className} style={{"margin": 0}}>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          {nav}
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
