name: Automated Release Deployment

on:
  push:
    branches: [ main ]

env:
  NODE_VERSION: 16.17.0

jobs:
  create-deployment-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build App Artifacts
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - run: |
          npm i
          npm run build
          tar -czf "${GITHUB_SHA}".tar.gz .output
      - name: Store app-artifacts for distribution
        uses: actions/upload-artifact@v3
        with:
          name: app-artifacts
          path: ${{ github.sha }}.tar.gz

  prepare-release-on-servers:
    needs: create-deployment-artifacts
    name: "Prepare release on INT server"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: app-artifacts
      - name: Upload app-artifacts
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: "22"
          username: "${{ secrets.SSH_USERNAME }}"
          key: ${{ secrets.SSH_KEY }}
          source: ${{ github.sha }}.tar.gz
          target: /home/emilmoham/artifacts
      - name: Extract archive and create directories
        uses: appleboy/ssh-action@master
        env:
          GITHUB_SHA: ${{ github.sha }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: "${{ secrets.SSH_USERNAME }}"
          key: ${{ secrets.SSH_KEY }}
          port: "22"
          envs: GITHUB_SHA
          script: |
            mkdir -p "/home/emilmoham/emilmoham.io/${GITHUB_SHA}"
            tar xzf /home/emilmoham/artifacts/${GITHUB_SHA}.tar.gz -C "/home/emilmoham/emilmoham.io/${GITHUB_SHA}"
            rm -rf /home/emilmoham/artifacts/${GITHUB_SHA}.tar.gz

  activate-release:
    name: "Activate release"
    runs-on: ubuntu-latest
    needs: prepare-release-on-servers
    steps:
      - name: Activate Release
        uses: appleboy/ssh-action@master
        env:
          GITHUB_SHA: ${{ github.sha }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: "${{ secrets.SSH_USERNAME }}"
          key: ${{ secrets.SSH_KEY }}
          port: "22"
          script: |
            pm2 delete website
            cd /home/emilmoham/emilmoham.io/${GITHUB_SHA}
            touch ecosystem.config.js
            echo "module.exports = {" >> ecosystem.config.js
            echo "  apps : [{" >> ecosystem.config.js
            echo "    name  : \"website\"," >> ecosystem.config.js
            echo "    script: \"./.output/server/index.mjs\"" >> ecosystem.config.js
            echo "  }]" >> ecosystem.config.js
            echo "}" >> ecosystem.config.js
            pm2 start
            pm2 save

  clean-up:
    name: "Clean up old versions"
    runs-on: ubuntu-latest
    needs: activate-release
    steps:
      - name: clean up old releases
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: "${{ secrets.SSH_USERNAME }}"
          key: ${{ secrets.SSH_KEY }}
          port: "22"
          script: |
            cd /home/emilmoham/emilmoham.io && ls -t -1 | tail -n +2 | xargs rm -rf
            cd /home/emilmoham/artifacts && rm -rf *
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: app-artifacts